
// ------------------------------------------------------------------------------------------------
// <auto-generated>
//  This code was generated by a C# code generator
//  Generated at 6/21/2018 11:57:45 AM
//
//  Warning: Do not make changes directly to this file; they will get overwritten on the next
//  code generation.
// </auto-generated>
// ------------------------------------------------------------------------------------------------
    
namespace ODataExamples.Repository.T4
{

  /// <summary>
  /// Product Brands
  /// </summary>
  public enum ProductBrandEnum : int
  {
 

  }
    
  /// <summary>
  /// Product Types
  /// </summary>
  public enum ProductTypeEnum : int
  {
 

  }
    
  /// <summary>
  /// Specification Types
  /// </summary>
  public enum SpecificationEnum : int
  {
 

  }
    
}
